FROM node:18-alpine

WORKDIR /app

# Copy everything
COPY . .

# Install dependencies
RUN npm install --legacy-peer-deps

# Expose port 8080
EXPOSE 8080

# Environment
ENV HOSTNAME=0.0.0.0
ENV PORT=8080

# Run dev server on port 8080
CMD ["npm", "run", "dev"]