[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node .next/standalone/server.js"

[variables]
NODE_VERSION = "20"
