[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = [
  'npm install -g pnpm@8',
  'pnpm config set store-dir ~/.pnpm-store',
  'pnpm install --no-frozen-lockfile'
]

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'

[variables]
NODE_ENV = 'production'
PORT = '3000'