import type { RequiredDataFromCollectionSlug } from 'payload'

// Static fallback for About Us page when database is not seeded
export const aboutStatic: RequiredDataFromCollectionSlug<'pages'> = {
  slug: 'about-us',
  _status: 'published',
  hero: {
    type: 'lowImpact',
    richText: {
      root: {
        type: 'root',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            tag: 'h1',
            type: 'heading',
            format: 'center',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: '小鳥と暮らす幸せな毎日へ',
                type: 'text',
                style: '',
                detail: 0,
                format: 1,
                version: 1,
              },
            ],
            direction: 'ltr',
          },
        ],
        direction: 'ltr',
      },
    },
  },
  layout: [
    {
      blockType: 'content',
      columns: [
        {
          size: 'full',
          richText: {
            root: {
              type: 'root',
              children: [
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: '私たちのビジョン' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: 'Kawaii Birdは、小鳥をペットとして飼育する方々のための総合情報サイトです。セキセイインコ、オカメインコ、フィンチなど、人気の小鳥たちの飼育方法、健康管理、栄養管理など、小鳥と幸せに暮らすための実践的な情報をお届けしています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: '私たちが大切にしていること' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'list',
                  listType: 'bullet',
                  version: 1,
                  children: [
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '🐦 小鳥の種類別の詳しい飼育ガイド' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '🏥 健康管理と病気予防の正確な情報' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '🥗 栄養バランスの取れた食事管理' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '🏠 快適なケージ環境の作り方' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '💝 小鳥との絆を深めるトレーニング方法' }
                      ],
                    },
                  ],
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: 'なぜ小鳥が大切なのか' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '小鳥たちは私たちの生活に彩りと癒しをもたらしてくれます。その愛らしい姿と美しい歌声は、日々のストレスから私たちを解放し、自然とのつながりを思い出させてくれます。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '私たちは、この素晴らしい小鳥たちの世界を、より多くの人々と共有したいと考えています。一緒に小鳥たちの魅力を探求し、彼らとの素敵な時間を過ごしましょう。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: '免責事項と重要なお知らせ' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: 'AI生成コンテンツについて', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトでは、記事の作成、画像の生成、翻訳などにAI（人工知能）技術を活用しています。AIによって生成されたコンテンツは、情報提供を目的としていますが、必ずしも正確性、完全性、最新性を保証するものではありません。重要な決定を行う際は、必ず専門家にご相談いただくか、複数の情報源を確認してください。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '情報の正確性について', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトに掲載されている情報は、一般的な情報提供を目的としており、専門的なアドバイスや指導を目的としたものではありません。鳥の健康や医療に関する事項については、必ず獣医師などの専門家にご相談ください。当サイトの情報を利用したことによる直接的または間接的な損害について、当サイトは一切の責任を負いかねます。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '知的財産権について', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトに掲載されているテキスト、画像、動画、その他のコンテンツの著作権は、当サイトまたはコンテンツ提供者に帰属します。これらのコンテンツを無断で複製、転載、配布、公開することは、著作権法により禁止されています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: 'ライセンスと使用条件', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトのコンテンツは、個人的な閲覧および非商業的な目的での使用に限り許可されています。商業目的での使用、再配布、または二次的著作物の作成を希望される場合は、事前に書面による許可を得る必要があります。第三者のコンテンツを使用している場合は、それぞれの権利者のライセンス条件に従ってください。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '外部リンクについて', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトから外部サイトへのリンクが含まれている場合がありますが、リンク先のサイトのコンテンツや運営について、当サイトは一切の責任を負いません。外部サイトをご利用の際は、そのサイトの利用規約やプライバシーポリシーをご確認ください。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '変更と更新', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトは、予告なくコンテンツの追加、変更、削除を行う権利を留保します。また、本免責事項も予告なく変更される場合があります。定期的にこのページをご確認いただくことをお勧めします。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: 'お問い合わせ' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '鳥に関するご質問やご意見、写真の投稿など、お気軽にお問い合わせください。私たちは鳥を愛するすべての方々からのメッセージをお待ちしています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              version: 1,
            },
          },
        },
      ],
    },
  ],
  meta: {
    title: 'わたしたちについて - Kawaii Bird',
    description: '日本と世界のかわいい小鳥たちの魅力を伝える、私たちのミッションとチームについて。',
  },
  title: 'わたしたちについて',
  id: 4,
  createdAt: '2025-09-02T14:25:19.974Z',
  updatedAt: '2025-09-15T14:59:31.213Z',
}