import type { RequiredDataFromCollectionSlug } from 'payload'

// Static fallback for About Us page when database is not seeded
export const aboutStatic: RequiredDataFromCollectionSlug<'pages'> = {
  slug: 'about-us',
  _status: 'published',
  hero: {
    type: 'lowImpact',
    richText: {
      root: {
        type: 'root',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            tag: 'h1',
            type: 'heading',
            format: 'center',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: '小鳥と暮らす幸せな毎日へ',
                type: 'text',
                style: '',
                detail: 0,
                format: 1,
                version: 1,
              },
            ],
            direction: 'ltr',
          },
        ],
        direction: 'ltr',
      },
    },
  },
  layout: [
    {
      blockType: 'content',
      columns: [
        {
          size: 'full',
          richText: {
            root: {
              type: 'root',
              children: [
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: '私たちのビジョン' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: 'Kawaii Birdは、小鳥をペットとして飼育する方々のための総合情報サイトです。セキセイインコ、オカメインコ、文鳥、フィンチなど、人気の小鳥たちの飼育方法、健康管理、栄養管理など、小鳥と幸せに暮らすための実践的な情報をお届けしています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: '運営者について' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトは、小鳥の飼育歴10年以上の愛鳥家チームによって運営されています。私たちは実際にセキセイインコ、オカメインコ、文鳥などを飼育しており、日々の経験から得た知識と、獣医師や専門家への取材を通じて、信頼性の高い情報をお届けしています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: '監修獣医師のご紹介' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトの記事は、以下の専門家による監修・アドバイスのもと作成されています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '鳥類専門獣医師 監修', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトでは、鳥類診療を専門とする獣医師の監修のもと、飼育情報や健康管理に関する記事を作成しています。特に病気の症状や治療に関する情報は、最新の獣医学的知見に基づいて記載されています。ただし、サイト上の情報は一般的な参考情報であり、個々の小鳥の症状については必ずかかりつけの獣医師にご相談ください。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '愛鳥家アドバイザー', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '編集部メンバーは全員が10年以上の小鳥飼育経験を持つ愛鳥家です。セキセイインコ、オカメインコ、文鳥、カナリア、十姉妹など、様々な小鳥との暮らしから得た実践的なノウハウをお伝えしています。日本愛玩動物協会の会員として、適切な飼育方法の普及にも努めています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: '私たちが大切にしていること' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'list',
                  listType: 'bullet',
                  version: 1,
                  children: [
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '正確性：獣医師監修のもと、科学的根拠に基づいた情報を提供' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '実践性：実際の飼育経験から得た、すぐに役立つアドバイス' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '安全性：小鳥の健康と安全を最優先にした情報発信' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '最新性：定期的な情報更新で、最新の飼育知識をお届け' }
                      ],
                    },
                  ],
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: 'コンテンツの特徴' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'list',
                  listType: 'bullet',
                  version: 1,
                  children: [
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '小鳥の種類別の詳しい飼育ガイド' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '健康管理と病気予防の正確な情報' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '栄養バランスの取れた食事管理' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '快適なケージ環境の作り方' }
                      ],
                    },
                    {
                      type: 'listitem',
                      version: 1,
                      children: [
                        { type: 'text', text: '小鳥との絆を深めるトレーニング方法' }
                      ],
                    },
                  ],
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: 'なぜ小鳥が大切なのか' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '小鳥たちは私たちの生活に彩りと癒しをもたらしてくれます。その愛らしい姿と美しい歌声は、日々のストレスから私たちを解放し、自然とのつながりを思い出させてくれます。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '私たちは、この素晴らしい小鳥たちの世界を、より多くの人々と共有したいと考えています。一緒に小鳥たちの魅力を探求し、彼らとの素敵な時間を過ごしましょう。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: '重要なお知らせ' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '医療アドバイスについて', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトに掲載されている情報は、一般的な情報提供を目的としており、専門的なアドバイスや指導を目的としたものではありません。小鳥の健康や医療に関する事項については、必ず獣医師などの専門家にご相談ください。当サイトの情報を利用したことによる直接的または間接的な損害について、当サイトは一切の責任を負いかねます。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '著作権について', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトに掲載されているテキスト、画像、動画、その他のコンテンツの著作権は、当サイトまたはコンテンツ提供者に帰属します。これらのコンテンツを無断で複製、転載、配布、公開することは、著作権法により禁止されています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h3',
                  children: [{ type: 'text', text: '外部リンクについて', detail: 0, format: 1, mode: 'normal', style: '', version: 1 }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '当サイトから外部サイトへのリンクが含まれている場合がありますが、リンク先のサイトのコンテンツや運営について、当サイトは一切の責任を負いません。外部サイトをご利用の際は、そのサイトの利用規約やプライバシーポリシーをご確認ください。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'heading',
                  tag: 'h2',
                  children: [{ type: 'text', text: 'お問い合わせ' }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
                {
                  type: 'paragraph',
                  children: [{
                    type: 'text',
                    text: '小鳥に関するご質問やご意見、写真の投稿など、お気軽にお問い合わせください。私たちは小鳥を愛するすべての方々からのメッセージをお待ちしています。',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    version: 1,
                  }],
                  direction: 'ltr',
                  format: '',
                  indent: 0,
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              version: 1,
            },
          },
        },
      ],
    },
  ],
  meta: {
    title: 'わたしたちについて | Kawaii Bird - 小鳥の飼育情報サイト',
    description: '小鳥の飼育歴10年以上の愛鳥家チームが運営する、信頼性の高い小鳥飼育情報サイトです。',
  },
  title: 'わたしたちについて',
  id: 4,
  createdAt: '2025-09-02T14:25:19.974Z',
  updatedAt: '2025-12-12T00:00:00.000Z',
}
